# Mise en place du notebook

In [1]:
# Paramètre(s) du notebook
ignore_warning=True
# ignore_warning=False

# VERBOSE=True
VERBOSE=True

OPTIONS=""
if not VERBOSE:
    OPTIONS="--quiet"

# Mise en place des bibliothèques

In [2]:
# Importation des librairies externes
!pip install git+https://github.com/InseeFrLab/Py-Insee-Data@52139da402bc33da6b8892d7d3208f1d2ddfaa02 --ignore-install PyYAML $OPTIONS
!pip install python-Levenshtein $OPTIONS
!pip install openpyxl $OPTIONS
!pip install fuzzywuzzy $OPTIONS
#!pip install pynsee[full]

Collecting git+https://github.com/InseeFrLab/Py-Insee-Data@52139da402bc33da6b8892d7d3208f1d2ddfaa02
  Cloning https://github.com/InseeFrLab/Py-Insee-Data (to revision 52139da402bc33da6b8892d7d3208f1d2ddfaa02) to /tmp/pip-req-build-jrachenr
  Running command git clone --filter=blob:none --quiet https://github.com/InseeFrLab/Py-Insee-Data /tmp/pip-req-build-jrachenr
  Running command git rev-parse -q --verify 'sha^52139da402bc33da6b8892d7d3208f1d2ddfaa02'
  Running command git fetch -q https://github.com/InseeFrLab/Py-Insee-Data 52139da402bc33da6b8892d7d3208f1d2ddfaa02
  Running command git checkout -q 52139da402bc33da6b8892d7d3208f1d2ddfaa02
  Resolved https://github.com/InseeFrLab/Py-Insee-Data to commit 52139da402bc33da6b8892d7d3208f1d2ddfaa02
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting PyYAML
  Downloading PyYAML-6.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (682 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 682.2/682.2 kB 15.2 MB/s eta 0:00:00a 0:00:01
Collecting unidecode>=1.2.0
  Downloading Unidecode-1.3.6-py3-none-any.whl (235 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 235.9/235.9 kB 5.0 MB/s eta 0:00:00a 0:00:01
Collecting pathlib2>=2.3.5
  Downloading pathlib2-2.3.7.post1-py2.py3-none-any.whl (18 kB)
Collecting pandas>=0.24.2
  Downloading pandas-1.5.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.1/12.1 MB 10.9 MB/s eta 0:00:0000:0100:01
Collecting tqdm>=4.56.0
  Downloading tqdm-4.64.1-py2.py3-none-any.whl (78 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.5/78.5 kB 21.0 MB/s eta 0:00:00
Collecting datetime>=3.5.9
  Downloading DateTime-4.7-py2.py3-none-any.whl (52 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.2/52.2 kB 17.4 MB/s eta 0:00:00
Collecting requests>=2.25.1
  Downloading requests-2.28.1-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 kB 17.8 MB/s eta 0:00:00
Collecting appdirs>=1.4.4
  Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting pytz
  Downloading pytz-2022.6-py2.py3-none-any.whl (498 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 498.1/498.1 kB 14.9 MB/s eta 0:00:00
Collecting zope.interface
  Downloading zope.interface-5.5.1-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (258 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 258.9/258.9 kB 16.3 MB/s eta 0:00:00
Collecting numpy>=1.21.0
  Downloading numpy-1.23.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.1/17.1 MB 16.1 MB/s eta 0:00:0000:0100:01
Collecting python-dateutil>=2.8.1
  Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.7/247.7 kB 10.2 MB/s eta 0:00:00
Collecting six
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting certifi>=2017.4.17
  Downloading certifi-2022.9.24-py3-none-any.whl (161 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 161.1/161.1 kB 39.3 MB/s eta 0:00:00
Collecting idna<4,>=2.5
  Downloading idna-3.4-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.5/61.5 kB 16.0 MB/s eta 0:00:00
Collecting charset-normalizer<3,>=2
  Downloading charset_normalizer-2.1.1-py3-none-any.whl (39 kB)
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.12-py2.py3-none-any.whl (140 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.4/140.4 kB 22.2 MB/s eta 0:00:00
Collecting setuptools
  Using cached setuptools-65.5.1-py3-none-any.whl (1.2 MB)
Building wheels for collected packages: pynsee
  Building wheel for pynsee (pyproject.toml) ... done
  Created wheel for pynsee: filename=pynsee-0.0.1-py3-none-any.whl size=44931166 sha256=c0c1111436cdc57599e3b497f71b663a836e2240cad54f88c8271075d3d48f3b
  Stored in directory: /home/onyxia/.cache/pip/wheels/91/1c/a4/b97cd4cfe37fcf99f2b02c860597971db714b5f22225cad15b
Successfully built pynsee
Installing collected packages: pytz, appdirs, urllib3, unidecode, tqdm, six, setuptools, PyYAML, numpy, idna, charset-normalizer, certifi, zope.interface, requests, python-dateutil, pathlib2, pandas, datetime, pynsee
Successfully installed PyYAML-6.0 appdirs-1.4.4 certifi-2022.9.24 charset-normalizer-2.1.1 datetime-4.7 idna-3.4 numpy-1.23.4 pandas-1.5.1 pathlib2-2.3.7.post1 pynsee-0.0.1 python-dateutil-2.8.2 pytz-2022.6 requests-2.28.1 setuptools-65.5.1 six-1.16.0 tqdm-4.64.1 unidecode-1.3.6 urllib3-1.26.12 zope.interface-5.5.1
Collecting python-Levenshtein
  Downloading python_Levenshtein-0.20.8-py3-none-any.whl (9.4 kB)
Collecting Levenshtein==0.20.8
  Downloading Levenshtein-0.20.8-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (174 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 174.1/174.1 kB 6.0 MB/s eta 0:00:00
Collecting rapidfuzz<3.0.0,>=2.3.0
  Downloading rapidfuzz-2.13.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 26.5 MB/s eta 0:00:0000:0100:01
Installing collected packages: rapidfuzz, Levenshtein, python-Levenshtein
Successfully installed Levenshtein-0.20.8 python-Levenshtein-0.20.8 rapidfuzz-2.13.2
Collecting openpyxl
  Downloading openpyxl-3.0.10-py2.py3-none-any.whl (242 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 242.1/242.1 kB 8.7 MB/s eta 0:00:00
Collecting et-xmlfile
  Downloading et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-1.1.0 openpyxl-3.0.10
Collecting fuzzywuzzy
  Downloading fuzzywuzzy-0.18.0-py2.py3-none-any.whl (18 kB)
Installing collected packages: fuzzywuzzy
Successfully installed fuzzywuzzy-0.18.0

In [3]:
# Importation des librairies classiques de python
import unicodedata
import requests
import time
import os
from tqdm import tqdm
import io
import warnings

# Importation des librairies de datascience et autres
import pandas as pd
import numpy as np
import pynsee
import pynsee.download
from pynsee.sirene import *
from pynsee.utils.init_conn import init_conn
from zipfile import ZipFile
from fuzzywuzzy import fuzz
from bs4 import BeautifulSoup

In [4]:
insee_key = "5L9J5YHbHq6lgCfv8ITH6f429VEa"
insee_secret = "XbyKQqhwVnofxT_ciBVksw8ffU8a"

In [5]:
# token API insee
#init_conn(insee_key=os.environ['INSEE_KEY'], insee_secret=os.environ['INSEE_SECRET'])
init_conn(insee_key=insee_key, insee_secret=insee_secret)

# Outils d'appareillement de code commune (qui varient d'année en année)

In [6]:
#le choix est fait de travailler en géographie de l'Insee 2021. 

cog_commune = pynsee.download.telechargerDonnees("COG_COMMUNE", date = "dernier")
URL_COG_2021="https://www.insee.fr/fr/statistiques/fichier/5057840/commune2021-csv.zip"

#Télécharger le zip de l'URL
r=requests.get(URL_COG_2021)

open("commune2021-csv.zip", 'wb').write(r.content)
    
    
with ZipFile("commune2021-csv.zip",'r') as myzip:
   data = myzip.open("commune2021.csv")

donnees_cog_2021=pd.read_csv(data,dtype=str)
# On enleve les communes associées,arrondissements et déléguées pour simplifier le dataframe
donnees_cog_2021=donnees_cog_2021[~donnees_cog_2021.TYPECOM.isin(["COMA","COMD","ARM"])]
donnees_cog_2021['NCC et DEP']= donnees_cog_2021['NCC'] + " " + donnees_cog_2021['DEP']
donnees_cog_2021['NCC et COM']= donnees_cog_2021['NCC'] + " ," + donnees_cog_2021['COM']

Data will be stored in the following location: /tmp/tmp_qewy5s3

Downloading:  96%|█████████▋| 1.65M/1.71M [00:00<00:00, 11.6MiB/s]
/opt/mamba/lib/python3.10/site-packages/pynsee/download/__init__.py:182: UserWarning: File in insee.fr modified or corrupted during download
  warnings.warn("File in insee.fr modified or corrupted during download")

No destination directory defined. Data have been written there: /tmp/tmp919syauw

Extracting: 100%|██████████| 6.86M/6.86M [00:00<00:00, 150MB/s]

In [7]:
donnees_cog_2021

,TYPECOM,COM,REG,DEP,CTCD,ARR,TNCC,NCC,NCCENR,LIBELLE,CAN,COMPARENT,NCC et DEP,NCC et COM
0,COM,01001,84,01,01D,012,5,ABERGEMENT CLEMENCIAT,Abergement-Clémenciat,L'Abergement-Clémenciat,0108,NaN,ABERGEMENT CLEMENCIAT 01,"ABERGEMENT CLEMENCIAT ,01001"
1,COM,01002,84,01,01D,011,5,ABERGEMENT DE VAREY,Abergement-de-Varey,L'Abergement-de-Varey,0101,NaN,ABERGEMENT DE VAREY 01,"ABERGEMENT DE VAREY ,01002"
2,COM,01004,84,01,01D,011,1,AMBERIEU EN BUGEY,Ambérieu-en-Bugey,Ambérieu-en-Bugey,0101,NaN,AMBERIEU EN BUGEY 01,"AMBERIEU EN BUGEY ,01004"
3,COM,01005,84,01,01D,012,1,AMBERIEUX EN DOMBES,Ambérieux-en-Dombes,Ambérieux-en-Dombes,0122,NaN,AMBERIEUX EN DOMBES 01,"AMBERIEUX EN DOMBES ,01005"
4,COM,01006,84,01,01D,011,1,AMBLEON,Ambléon,Ambléon,0104,NaN,AMBLEON 01,"AMBLEON ,01006"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37737,COM,97613,06,976,976D,NaN,0,M TSANGAMOUJI,M'Tsangamouji,M'Tsangamouji,97613,NaN,M TSANGAMOUJI 976,"M TSANGAMOUJI ,97613"
37738,COM,97614,06,976,976D,NaN,1,OUANGANI,Ouangani,Ouangani,97610,NaN,OUANGANI 976,"OUANGANI ,97614"
37739,COM,97615,06,976,976D,NaN,0,PAMANDZI,Pamandzi,Pamandzi,97611,NaN,PAMANDZI 976,"PAMANDZI ,97615"
37740,COM,97616,06,976,976D,NaN,0,SADA,Sada,Sada,97612,NaN,SADA 976,"SADA ,97616"
37741,COM,97617,06,976,976D,NaN,0,TSINGONI,Tsingoni,Tsingoni,97613,NaN,TSINGONI 976,"TSINGONI ,97617"

In [8]:
display(donnees_cog_2021.describe())

,TYPECOM,COM,REG,DEP,CTCD,ARR,TNCC,NCC,NCCENR,LIBELLE,CAN,COMPARENT,NCC et DEP,NCC et COM
count,34965,34965,34965,34965,34965,34948,34965,34965,34965,34965,34849,0,34965,34965
unique,1,34965,18,101,100,332,8,32488,32553,32707,2039,0,34963,34965
top,COM,01001,44,62,62D,621,0,SAINTE COLOMBE,Sainte-Colombe,Sainte-Colombe,5723,NaN,LONGEVILLE 25,"ABERGEMENT CLEMENCIAT ,01001"
freq,34965,1,5121,890,890,357,28696,12,12,12,135,NaN,2,1

In [7]:
#fonction pour trouver une commune à partir d'un libellé (codage/codification) à l'aide de la librairie fuzzywuzzy

In [9]:
def trouve_commune_with_fuzz(libelle,dep):
    mondf=donnees_cog_2021[donnees_cog_2021['DEP']==dep]
    mondf['score']=mondf['NCC'].apply(lambda x: fuzz.token_sort_ratio(x,libelle))
    mondf=mondf.sort_values(by="score",ascending=False)
    return mondf['NCC et COM'].iloc[0]

if not donnees_cog_2021.empty:
    print("2 - Téléchargement du Code Officiel Géographi  ====> c'est bon ")
else:
    print("2 - Téléchargement du Code Officiel Géographi  ====> c'est pas bon ")

2 - Téléchargement du Code Officiel Géographi  ====> c'est bon

# Récupérations de données socio-économiques à partir de divers sources

##### [Utilisation de l'API des fichiers locaux](https://api.insee.fr/catalogue/site/themes/wso2/subthemes/insee/pages/item-info.jag?name=DonneesLocales&version=V0.1&provider=insee#tab2) de l'INSEE

In [10]:
# version graphique : https://api.insee.fr/catalogue/site/themes/wso2/subthemes/insee/pages/item-info.jag?name=DonneesLocales&version=V0.1&provider=insee#!/default/getDonnees 
# Commmande cURL équivalente
# curl -X GET --header 'Accept: application/xml' --header 'Authorization: Bearer 1be1a6b6-2e8e-335e-8a5d-91607845b110' 'https://api.insee.fr/donnees-locales/V0.1/donnees/geo-INDICS_FILO_DISP_DET@GEO2021FILO2019/COM-75056.1'

In [11]:
headers = {
    'Accept':'application/xml'
}

Malheureusement l'API est limitée : on ne peut télécharger qu'une fiche par une fiche et 30 fiches par jours par clé. Vu qu'une fiche correspond à une commune c'est limité. Une telle API a son utilisé si on veut mettre un place un outil de recherche graphique comme [l'INSEE l'a fait](https://www.insee.fr/fr/statistiques/zones/6037462). Pour notre utilité cela est limitée, c'est d'ailleurs expliqué sur la [page](https://api.insee.fr/catalogue/site/themes/wso2/subthemes/insee/pages/item-info.jag?name=DonneesLocales&version=V0.1&provider=insee#tab2:~:text=Nota%20Bene%C2%A0%3A%20Les%20bases%20de%20donn%C3%A9es%20du%20RP%20mises%20%C3%A0%20disposition%20sur%20insee.fr%20ne%20sont%20pas%20soumises%20%C3%A0%20ces%20restrictions%2C%20notamment%20pour%20permettre%20un%20usage%20expert%20des%20donn%C3%A9es%20et%20la%20reconstitution%20%C3%A9ventuelle%20d%E2%80%99information%20sur%20des%20regroupements%20de%20communes%20%C3%A0%20fa%C3%A7on).

## Téléchargements directs depuis le site de l'INSEE (à défaut de l'utilisation de l'API pas encore suffisament opérationnelle)

### Téléchargement des données Filosofi avec les principaux indicateurs de pauvreté et de revenus

In [86]:
# URL de la page à télécharger : https://www.insee.fr/fr/statistiques/6036902
URL_FILO_ZIP_2019="https://www.insee.fr/fr/statistiques/fichier/6036902/base-cc-filosofi-2019_CSV.zip"
nom = URL_FILO_ZIP_2019.split('/')[-1]
response=requests.get(URL_FILO_ZIP_2019)
if response.status_code == 200:
        with open(nom, 'wb') as f:
            f.write(response.content)
with ZipFile(nom, 'r') as zipfile :
    nom_fichier_data = "cc_filosofi_2019_COM.csv"
    nom_fichier_meta = "meta_"+nom_fichier_data
    data = zipfile.open(nom_fichier_data)
    meta = zipfile.open(nom_fichier_meta)
donnees_filo_ind_communes_2019=pd.read_csv(data, sep=";", low_memory=False) 
table_var_filo_ind_com_2019 = pd.read_csv(meta, sep=";", low_memory=False)

In [13]:
donnees_filo_ind_communes_2019.head()

,CODGEO,NBMENFISC19,NBPERSMENFISC19,MED19,PIMP19,TP6019,TP60AGE119,TP60AGE219,TP60AGE319,TP60AGE419,...,PPEN19,PPAT19,PPSOC19,PPFAM19,PPMINI19,PPLOGT19,PIMPOT19,D119,D919,RD19
0,01001,322,819,23970,s,s,s,s,s,s,...,s,s,s,s,s,s,s,s,s,s
1,01002,113,263,23640,s,s,s,s,s,s,...,s,s,s,s,s,s,s,s,s,s
2,01004,6711,15040,20510,56,18,21,23,21,16,...,"25,6","12,3","7,7","2,8","3,1","1,8","-15,7",11080,35230,"3,2"
3,01005,720,1823,24050,s,s,s,s,s,s,...,s,s,s,s,s,s,s,s,s,s
4,01006,s,s,s,s,s,s,s,s,s,...,s,s,s,s,s,s,s,s,s,s

In [17]:
table_var_filo_ind_com_2019.sample(10)

,COD_VAR,LIB_VAR,LIB_VAR_LONG,COD_MOD,LIB_MOD,TYPE_VAR,LONG_VAR
30197,CODGEO,Code géographique,Code géographique,77176,Faremoutiers,CHAR,5
21107,CODGEO,Code géographique,Code géographique,57328,Holacourt,CHAR,5
31586,CODGEO,Code géographique,Code géographique,80573,Morvillers-Saint-Saturnin,CHAR,5
560,CODGEO,Code géographique,Code géographique,02145,Caumont,CHAR,5
5085,CODGEO,Code géographique,Code géographique,15117,Marcolès,CHAR,5
32463,CODGEO,Code géographique,Code géographique,83130,Solliès-Pont,CHAR,5
23490,CODGEO,Code géographique,Code géographique,61444,Saint-Philbert-sur-Orne,CHAR,5
33225,CODGEO,Code géographique,Code géographique,87067,Folles,CHAR,5
5887,CODGEO,Code géographique,Code géographique,17311,Saint-Augustin,CHAR,5
8346,CODGEO,Code géographique,Code géographique,24500,Saint-Sauveur-Lalande,CHAR,5

### Téléchargement des données des populations légales du millénisme 2019

In [18]:
#Téléchargement des populations légales du millénisme 2018 
URL_POP_LEG="https://www.insee.fr/fr/statistiques/fichier/6011070/ensemble.zip"

#Télécharger le zip de l'URL
r=requests.get(URL_POP_LEG)

open("ensemble.zip", 'wb').write(r.content)
    
    
with ZipFile("ensemble.zip",'r') as myzip:
    data = myzip.open("donnees_communes.csv")

donnees_pop_leg_19=pd.read_csv(data,sep=';',dtype=str)
donnees_pop_leg_19["CODE_INSEE"]=donnees_pop_leg_19["CODDEP"]+donnees_pop_leg_19["CODCOM"]
donnees_pop_leg_19=donnees_pop_leg_19.set_index("CODE_INSEE")

In [47]:
if VERBOSE:
    display(donnees_pop_leg_19.head(10))
if VERBOSE:
    display(donnees_pop_leg_19.describe())
   
if not donnees_pop_leg_19.empty:
    print("6 - Téléchargement des populations légales  ====> c'est bon ")
else:
    print("6 - Téléchargement des populations légales  ====> c'est pas bon ")

,CODREG,REG,CODDEP,CODARR,CODCAN,CODCOM,COM,PMUN,PCAP,PTOT
CODE_INSEE,,,,,,,,,,
01001,84,Auvergne-Rhône-Alpes,01,2,08,001,L'Abergement-Clémenciat,779,19,798
01002,84,Auvergne-Rhône-Alpes,01,1,01,002,L'Abergement-de-Varey,256,1,257
01004,84,Auvergne-Rhône-Alpes,01,1,01,004,Ambérieu-en-Bugey,14134,380,14514
01005,84,Auvergne-Rhône-Alpes,01,2,22,005,Ambérieux-en-Dombes,1751,25,1776
01006,84,Auvergne-Rhône-Alpes,01,1,04,006,Ambléon,112,6,118
01007,84,Auvergne-Rhône-Alpes,01,1,01,007,Ambronay,2800,115,2915
01008,84,Auvergne-Rhône-Alpes,01,1,01,008,Ambutrix,762,15,777
01009,84,Auvergne-Rhône-Alpes,01,1,04,009,Andert-et-Condon,326,9,335
01010,84,Auvergne-Rhône-Alpes,01,1,10,010,Anglefort,1105,17,1122
01011,84,Auvergne-Rhône-Alpes,01,4,14,011,Apremont,368,11,379

,CODREG,REG,CODDEP,CODARR,CODCAN,CODCOM,COM,PMUN,PCAP,PTOT
count,34990,34990,34990,34990,34990,34990,34990,34990,34990,34990
unique,17,17,100,9,59,908,32732,5899,719,5930
top,44,Grand Est,62,2,02,077,Sainte-Colombe,139,3,117
freq,5121,5121,890,10778,1885,89,12,76,2338,73

6 - Téléchargement des populations légales  ====> c'est bon

### Téléchargement des données d'emploi localisées

In [20]:

URL_TAUX_CHOMAGE_15_24_PAR_COM="https://www.observatoire-des-territoires.gouv.fr/outils/cartographie-interactive/api/v1/functions/GC_API_download.php?type=stat&nivgeo=com2021&dataset=indic_sex_rp&indic=tx_chom1524"


donnees_chomage_15_24_par_com=pd.read_excel(URL_TAUX_CHOMAGE_15_24_PAR_COM, sheet_name='Data',skiprows=4)

In [46]:
if VERBOSE:
   display(donnees_chomage_15_24_par_com.head(10))

  codgeo                   libgeo    an sexe  tx_chom1524
0  01001  L'Abergement-Clémenciat  2008    F          8.3
1  01001  L'Abergement-Clémenciat  2008    H         13.8
2  01001  L'Abergement-Clémenciat  2008    T         12.2
3  01001  L'Abergement-Clémenciat  2013    F         16.7
4  01001  L'Abergement-Clémenciat  2013    H         38.5
5  01001  L'Abergement-Clémenciat  2013    T         28.0
6  01001  L'Abergement-Clémenciat  2018    F         42.9
7  01001  L'Abergement-Clémenciat  2018    H         26.3
8  01001  L'Abergement-Clémenciat  2018    T         30.8
9  01002    L'Abergement-de-Varey  2008    F         50.0

In [22]:
donnees_chomage_15_24_par_com_travail=donnees_chomage_15_24_par_com[donnees_chomage_15_24_par_com["an"]==2019]
donnees_chomage_15_24_par_com_travail=donnees_chomage_15_24_par_com_travail[donnees_chomage_15_24_par_com_travail["sexe"]=="T"]
donnees_chomage_15_24_par_com_travail=donnees_chomage_15_24_par_com_travail.set_index("codgeo")

In [23]:
if VERBOSE:
    display(donnees_chomage_15_24_par_com_travail)
if not donnees_chomage_15_24_par_com_travail.empty:
    print("7 - Téléchargement des données d'emplois localisées  ====> c'est bon ")
else:
    print("7 - Téléchargement des données d'emplois localiséess  ====> c'est pas bon ")

Empty DataFrame
Columns: [libgeo, an, sexe, tx_chom1524]
Index: []

7 - Téléchargement des données d'emplois localiséess  ====> c'est pas bon

In [24]:
%store donnees_filo_ind_communes_2019

Stored 'donnees_filo_ind_communes_2019' (DataFrame)

Réalisation d'une grosse base de données avec toutes les données Filosofi

In [89]:
# Données d'emploi localisées
base_travail = donnees_chomage_15_24_par_com[['codgeo','tx_chom1524']][donnees_chomage_15_24_par_com['an']==2018][donnees_chomage_15_24_par_com['sexe']=="T"]
base_travail.rename(columns={'tx_chom1524':'tx_chom1524_T'}, inplace=True)
base_travail = base_travail.merge(donnees_chomage_15_24_par_com[['codgeo','tx_chom1524']][donnees_chomage_15_24_par_com['an']==2018][donnees_chomage_15_24_par_com['sexe']=="H"], how='left', on='codgeo')
base_travail.rename(columns={'tx_chom1524':'tx_chom1524_H'}, inplace=True)
base_travail = base_travail.merge(donnees_chomage_15_24_par_com[['codgeo','tx_chom1524']][donnees_chomage_15_24_par_com['an']==2018][donnees_chomage_15_24_par_com['sexe']=="F"], how='left', on='codgeo')
base_travail.rename(columns={'tx_chom1524':'tx_chom1524_F'}, inplace=True)

# Données de population
donnees_pop_leg_19.head()
donnees_pop_leg_19 = donnees_pop_leg_19.assign(codgeo = donnees_pop_leg_19['CODDEP'] + donnees_pop_leg_19['CODCOM'])
donnees_pop_leg_19['PTOT'] = donnees_pop_leg_19['PTOT'].astype({'PTOT':float})
base_travail = base_travail.merge(donnees_pop_leg_19[['codgeo','PTOT']], on = 'codgeo')
base_travail.rename(columns={'PTOT':'pop_tot'}, inplace=True)

# Données socio-économiques
donnees_filo_ind_communes_2019.rename(columns={'CODGEO':'codgeo'}, inplace=True)
donnees_filo_ind_communes_2019['MED19'] = donnees_filo_ind_communes_2019['MED19'].replace({'s':-10})
donnees_filo_ind_communes_2019 = donnees_filo_ind_communes_2019.astype({'MED19':float})
base_travail = base_travail.merge(donnees_filo_ind_communes_2019[['codgeo','MED19']], on = 'codgeo')
base_travail.rename(columns={'MED19':'rev_median'}, inplace=True)
base_travail.sample(10)

/tmp/ipykernel_229/4175857912.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  base_travail = donnees_chomage_15_24_par_com[['codgeo','tx_chom1524']][donnees_chomage_15_24_par_com['an']==2018][donnees_chomage_15_24_par_com['sexe']=="T"]
/tmp/ipykernel_229/4175857912.py:4: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  base_travail = base_travail.merge(donnees_chomage_15_24_par_com[['codgeo','tx_chom1524']][donnees_chomage_15_24_par_com['an']==2018][donnees_chomage_15_24_par_com['sexe']=="H"], how='left', on='codgeo')
/tmp/ipykernel_229/4175857912.py:6: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  base_travail = base_travail.merge(donnees_chomage_15_24_par_com[['codgeo','tx_chom1524']][donnees_chomage_15_24_par_com['an']==2018][donnees_chomage_15_24_par_com['sexe']=="F"], how='left', on='codgeo')

      codgeo  tx_chom1524_T  tx_chom1524_H  tx_chom1524_F  pop_tot  rev_median
16284  44094           14.5           15.6           13.2   3309.0     24780.0
6176   18168            0.0            0.0            NaN    219.0     20330.0
25203  64362           16.7            7.7           40.0    432.0     21750.0
27931  71160            0.0            0.0            0.0    319.0     22480.0
6089   18080           33.3           50.0            0.0    154.0     21120.0
33072  86286           23.8            0.0           33.3    393.0     18850.0
17438  48094           10.5           12.0            7.7    987.0     21270.0
33252  87174           21.9           11.1           35.7   1250.0     22100.0
27883  71110           28.6            8.3           55.6    575.0     20220.0
9854   27649           30.0           28.6           33.3    360.0     23140.0

Nous allons maintennat procéder au nettoyage des données :

In [90]:
display(base_travail.describe())
base_travail.isna().sum()

,tx_chom1524_T,tx_chom1524_H,tx_chom1524_F,pop_tot,rev_median
count,34086.000000,33375.000000,32355.000000,34814.000000,34814.000000
mean,24.549991,23.278622,26.411145,1801.663038,19805.326018
std,16.708724,19.249051,22.784438,7953.341393,7282.589139
min,0.000000,0.000000,0.000000,1.000000,-10.000000
25%,14.600000,10.350000,10.700000,202.000000,19580.000000
50%,23.500000,21.800000,25.000000,465.000000,21270.000000
75%,33.300000,33.300000,36.000000,1175.000000,23190.000000
max,100.000000,100.000000,100.000000,498596.000000,51720.000000

codgeo              0
tx_chom1524_T     728
tx_chom1524_H    1439
tx_chom1524_F    2459
pop_tot             0
rev_median          0
dtype: int64